# Generated by Django 4.2.7 on 2024-05-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rub', models.CharField(max_length=255)),
                ('Usdt', models.CharField(max_length=255)),
            ],
        ),
    ]
